INSERT INTO category (category_name) VALUES ("Apparel & Accessories"),
("Books & Audible"),
("Movies, Music & Games"),
("Electronics, Computers & Office"),
("Home, Garden & Tools"),
("Pet Supplies"),
("Food & Grocery"),
("Health & Beauty"),
("Toys, Kids & Baby"),
("Sports & Outdoors"),
("Automotive & Industrial"),
("Services"),
("Charity"),
("Women"),
("Men"),
("Girls"),
("Boys"),
("Baby"),
("Luggage"),
("Books"),
("Children's Books"),
("Comics & Graphic Novels"),
("Magazines"),
("Textbooks"),
("Audiobooks"),
("Movies & TV Shows"),
("Blu-ray"),
("CDs & Vinyl"),
("Digital Music"),
("Musical Instruments"),
("Video Games"),
("PC Games"),
("TV & Video"),
("Home Audio & Theater"),
("Headphones"),
("Camera, Photo & Video"),
("Cell Phones & Accessories"),
("Bluetooth & Wireless Speakers"),
("Car Electronics"),
("Wearable Technology"),
("Computer & Office"),
("Computers, Tablets & PC Products"),
("Monitors"),
("Accessories"),
("Networking"),
("Drives & Storage"),
("Computer Parts & Components"),
("Software"),
("Printers & Ink"),
("Office & School Supplies"),
("Home Decor"),
("Furniture"),
("Kitchen & Dining"),
("Bed & Bath"),
("Garden & Outdoors"),
("Mattresses"),
("Lighting"),
("Storage & Organization"),
("Appliances"),
("Fine Arts"),
("Collectibles"),
("Arts, Crafts & Sewing"),
("Event & Party Supplies"),
("Home Improvement"),
("Power & Hand Tools"),
("Lamps & Light Fixtures"),
("Kitchen & Bath Fixtures"),
("Hardware"),
("Smart Home"),
("Dog Food & Supplies"),
("Cat Food & Supplies"),
("Fish & Aquatic Pets"),
("Small Animals"),
("Birds"),
("Beauty Products"),
("Health & Wellness"),
("Toys & Games"),
("Baby Products"),
("Exercise & Fitness"),
("Hunting & Fishing"),
("Team Sports"),
("Golf"),
("Leisure Sports & Game Room"),
("Sports Collectibles"),
("Camping & Hiking"),
("Cycling & Scooters"),
("Skateboards & Skates"),
("Water Sports"),
("Winter Sports"),
("Climbing"),
("Automotive Parts & Accessories"),
("Automotive Tools & Equipment"),
("Tires & Wheels"),
("Motorcycle & Powersports"),
("Vehicles"),
("Garage Supplies");

INSERT INTO parent_child_categories (parent_category_id, child_category_id) VALUES
(1, 13),
(1, 14),
(1, 15),
(1, 16),
(1, 17),
(1, 18),

(2, 19),
(2, 20),
(2, 21),
(2, 22),
(2, 23),
(2, 24),

(3, 25),
(3, 26),
(3, 27),
(3, 28),
(3, 29),
(3, 30),
(3, 31),

(4, 32),
(4, 33),
(4, 34),
(4, 35),
(4, 36),
(4, 37),
(4, 38),
(4, 39),
(4, 40),

(40, 41),
(40, 42),
(40, 43),
(40, 44),
(40, 45),
(40, 46),
(40, 47),
(40, 48),
(40, 49),

(5, 50),
(5, 51),
(5, 52),
(5, 53),
(5, 54),
(5, 55),
(5, 56),
(5, 57),
(5, 58),
(5, 59),
(5, 60),
(5, 61),
(5, 62),
(5, 63),
(5, 64),
(5, 65),
(5, 66),
(5, 67),
(5, 68),

(6, 69),
(6, 70),
(6, 71),
(6, 72),
(6, 73),

(8, 74),
(8, 75),

(9, 76),
(9, 77),

(10, 78),
(10, 79),
(10, 80),
(10, 81),
(10, 82),
(10, 83),
(10, 84),
(10, 85),
(10, 86),
(10, 87),
(10, 88),
(10, 89),

(11, 90),
(11, 91),
(11, 92),
(11, 93),
(11, 94),
(11, 95);

-- subcategories under womens clothing (please save for later)
-- ("Clothing"),
-- ("Shoes"),
-- ("Jewelry"),
-- ("Watches"),
-- ("Handbags & Wallets"),
-- ("Accessories"),
-- ("Dresses"),
-- ("Tops, Tees & Blouses"),
-- ("Sweathers"),
-- ("Hoodies & Sweatshirts"),
-- ("Jeans"),
-- ("Pants"),
-- ("Skirts"),
-- ("Shorts"),
-- ("Leggings"),
-- ("Active"),
-- ("Swimsuits & Cover Ups"),
-- ("Lingerie, Sleep & Lounge"),
-- ("Jumpsuits, Rompers & Overalls"),
-- ("Coats, Jackets & Vests"),
-- ("Suiting & Blazers"),
-- ("Socks & Hosiery"),
-- ("Casual"),
-- ("Club & Night Out"),
-- ("Cocktail"),
-- ("Formal"),
-- ("Work"),
-- ("Wedding Dresses"),
-- ("Blouses & Button-Down"),
-- ("Shirts"),
-- ("Knits & Tees"),
-- ("Polos"),
-- ("Tanks & Camis"),
-- ("Tunics"),
-- ("Vests"),
-- ("Cardigans"),
-- ("Pullovers"),
-- ("Shrugs"),
-- ("Vests"),
-- ("Casual"),
-- ("Wear to Work"),
-- ("Night Out")

